crds:
  install: true

image:
  repository: ghcr.io/opensource-thg/cockroachdb-operator
  pullPolicy: IfNotPresent
  tag: ""

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deployment:
  labels: {}
  annotations: {}

podAnnotations: {}

podEnvFrom: {}

podSecurityContext:
  enabled: true
  fsGroup: 2000

securityContext:
  enabled: true
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi
