{{ if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.cockroachdb.ics.cloud
spec:
  group: cockroachdb.ics.cloud
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
    - db
    - dbs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                cockroachRootSecret:
                  type: string
                  description: The TLS secret containing the root cert and key along with the cluster CA cert
                    Defaults to cockroachdb-root if omitted.
                cockroachServiceName:
                  type: string
                  description: The name of the service used to communicate with CockroachDB.
                    Defaults to cockroachdb-public.{namespace} if omitted.
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.cockroachdb.ics.cloud
spec:
  group: cockroachdb.ics.cloud
  scope: Namespaced
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
    - user
    - users
    - dbusers
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                databaseGrants:
                  type: array
                  description: The grants to be granted to the user.
                  items:
                    type: object
                    properties:
                      database:
                        type: string
                        description: The database for the grants to be assigned to.
                      grant:
                        type: string
                        description: The grant to be applied to the specified database for the given user.
                    required:
                      - database
                      - grant
                tableGrants:
                  type: array
                  description: The grants to be granted to the user.
                  items:
                    type: object
                    properties:
                      database:
                        type: string
                        description: The database for the grants to be assigned to.
                      table:
                        type: string
                        description: The table for the grants to be assigned to.
                      grant:
                        type: string
                        description: The grant to be applied to the specified table for the given user.
                    required:
                      - database
                      - table
                      - grant
                credentialsSecret:
                  type: string
                  description: The secret to store the username and password into. If the secret already exists then the password
                    from that will be used.
                credentialsSecretUsernameKey:
                  type: string
                  description: The key used to store the username under in the credentialsSecret.
                    Defaults to COCKROACHDB_USERNAME.
                credentialsSecretPasswordKey:
                  type: string
                  description: The key used to store the username under in the credentialsSecret.
                    Defaults to COCKROACHDB_PASSWORD.
                cockroachRootSecret:
                  type: string
                  description: The TLS secret containing the root cert and key along with the cluster CA cert.
                    Defaults to cockroachdb-root if omitted.
                cockroachServiceName:
                  type: string
                  description: The name of the service used to communicate with CockroachDB.
                    Defaults to cockroachdb-public if omitted.
              required:
                - databaseGrants
                - tableGrants
                - credentialsSecret
      additionalPrinterColumns:
        - name: Cred Secret
          type: string
          jsonPath: .spec.credentialsSecret
        - name: Database Grants
          type: string
          jsonPath: .spec.databaseGrants
        - name: Table Grants
          type: string
          jsonPath: .spec.tableGrants
{{ end }}
