apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.cockroachdb.thg.com
spec:
  group: cockroachdb.thg.com
  scope: Namespaced
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
    - db
    - dbs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              properties:
                cockroachRootSecret:
                  type: string
                  description: The TLS secret containing the root cert and key along with the cluster CA cert
                    Defaults to cockroachdb-root if omitted.
                cockroachServiceName:
                  type: string
                  description: The name of the service used to communicate with CockroachDB.
                    Defaults to cockroachdb-public.{namespace} if omitted.